# Configuración de H2 (Base de Datos en RAM)
spring.datasource.url=jdbc:h2:mem:fraudguard_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que podamos ver la base de datos en el navegador
spring.h2.console.enabled=true

# Mostrar el SQL que hace Spring en la consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update